# This is a basic workflow to help you get started with Actions

name: Build Python Project on Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7' # Cambia según la versión de Python que uses

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Asegúrate de tener pip actualizado
          pip install Flask Django Waitress app  # Instala Flask, Django, Waitress y app directamente
          #pip install -r requirements.txt        # Instala dependencias adicionales desde un archivo si existe

      # 4. Prueba de compilación o ejecución
      - name: Test the project
        run: python -c "print('Dependencies installed and build successful!')"
